# Generated by Django 5.2.8 on 2025-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
