# Generated by Django 5.2.8 on 2025-12-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_contact_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="discount_price",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="dishes",
        ),
        migrations.AddField(
            model_name="booking",
            name="time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="core.shop",
            ),
        ),
    ]
