# Generated by Django 5.2.8 on 2025-12-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dish_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
