# Generated by Django 5.2.7 on 2025-11-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_review_listing_alter_review_rating_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
