# Generated by Django 5.2.8 on 2025-12-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_booking_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="discount_price",
        ),
    ]
