# Generated by Django 5.2.7 on 2025-11-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listing_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='e.g. Mon-Sun: 10am - 10pm', max_length=255, null=True),
        ),
    ]
