# Generated by Django 6.0 on 2025-12-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_experience_discount_price_remove_shop_dishes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="category",
        ),
        migrations.AddField(
            model_name="shop",
            name="dining_establishment_type",
            field=models.CharField(
                choices=[
                    ("fine_dining", "Fine-dining restaurant"),
                    ("popular_themed_cafe", "Popular themed café"),
                    (
                        "high_demand_eatery",
                        "High-demand eatery (Michelin-starred or celebrity-chef)",
                    ),
                    ("hawker_centre", "Hawker centre"),
                    ("food_court", "Food court"),
                    ("casual_cafe", "Casual café"),
                    ("fast_food_outlet", "Fast-food outlet"),
                ],
                default="casual_cafe",
                max_length=50,
            ),
        ),
    ]
