# Generated by Django 6.0 on 2025-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_shop_category_shop_dining_establishment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="opening_hours_structured",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
