# Generated by Django 6.0 on 2025-12-05 17:36

import re
import json
from django.db import migrations

def convert_to_24_hour_format(time_str):
    if not time_str: return None
    time_str = str(time_str).strip().lower()
    match = re.search(r'(\d{1,2})[:.]?(\d{2})?\s*(am|pm)', time_str)
    if match:
        hour, minute, period = match.groups()
        hour = int(hour)
        minute = int(minute) if minute else 0
        if period == 'pm' and hour != 12: hour += 12
        elif period == 'am' and hour == 12: hour = 0
        return f"{hour:02d}:{minute:02d}"
    match = re.search(r'(\d{1,2})[:.]?(\d{2})?', time_str)
    if match:
        hour, minute = match.groups()
        return f"{int(hour):02d}:{int(minute) if minute else 0:02d}"
    return None

def get_day_range(start_day_str, end_day_str):
    days_map = {
        "mon": 1, "tue": 2, "wed": 3, "thu": 4, "fri": 5, "sat": 6, "sun": 7,
        "monday": 1, "tuesday": 2, "wednesday": 3, "thursday": 4, "friday": 5, "saturday": 6, "sunday": 7
    }
    start_day = days_map.get(start_day_str[:3].lower())
    end_day = days_map.get(end_day_str[:3].lower())
    if start_day is None or end_day is None: return []
    if start_day <= end_day: return list(range(start_day, end_day + 1))
    else: return list(range(start_day, 8)) + list(range(1, end_day + 1))

def process_shop_hours(shop):
    if not shop.opening_hours: return []
    text = shop.opening_hours.lower().replace('–', '-')
    structured_hours = []

    # Exclude closed days first
    closed_days_match = re.search(r'closed on (\w+)', text)
    closed_day = None
    if closed_days_match:
        days_map = { "monday": 1, "tuesday": 2, "wednesday": 3, "thursday": 4, "friday": 5, "saturday": 6, "sunday": 7 }
        closed_day_str = closed_days_match.group(1)
        closed_day = days_map.get(closed_day_str, days_map.get(closed_day_str + "s"))


    clauses = re.split(r',|;', text)

    for clause in clauses:
        clause = clause.strip()
        if not clause or 'closed' in clause: continue

        days = []
        # Look for day ranges (e.g., "tuesday to saturday")
        day_range_match = re.search(r'\b(mon|tue|wed|thu|fri|sat|sun)\w*\s*(?:to|-)\s*(mon|tue|wed|thu|fri|sat|sun)\w*\b', clause)
        if day_range_match:
            days.extend(get_day_range(day_range_match.group(1), day_range_match.group(2)))
        else: # Look for individual days
            for day_str, day_num in {"monday": 1, "tuesday": 2, "wednesday": 3, "thursday": 4, "friday": 5, "saturday": 6, "sunday": 7}.items():
                 if day_str in clause or day_str[:3] in clause:
                     days.append(day_num)

        if not days and 'daily' in clause:
            days = list(range(1, 8))

        times = re.findall(r'(\d{1,2}(?:[:.]\d{2})?\s*(?:am|pm)?)', clause)

        if 'seatings' in clause or '&' in clause:
            for day_num in days:
                if day_num == closed_day: continue
                for t in times:
                    open_time = convert_to_24_hour_format(t)
                    if open_time:
                        close_hour = int(open_time.split(':')[0]) + 2
                        structured_hours.append({"day_of_week": day_num, "open_time": open_time, "close_time": f"{close_hour:02d}:{open_time.split(':')[1]}"})
        elif len(times) >= 2:
            open_time = convert_to_24_hour_format(times[0])
            close_time = convert_to_24_hour_format(times[-1])
            for day_num in days:
                if day_num == closed_day: continue
                structured_hours.append({"day_of_week": day_num, "open_time": open_time, "close_time": close_time})


    unique_hours = [dict(t) for t in {tuple(d.items()) for d in structured_hours}]
    return sorted(unique_hours, key=lambda x: x['day_of_week'])


def parse_opening_hours(apps, schema_editor):
    Shop = apps.get_model('core', 'Shop')
    for shop in Shop.objects.all():
        shop.opening_hours_structured = process_shop_hours(shop)
        shop.save()


def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_shop_opening_hours_structured"),
    ]

    operations = [
        migrations.RunPython(parse_opening_hours, do_nothing),
    ]
